### ISSUE TITLE
d7b745e5a broke builds using wgpu-rs git repo as dependency

### ISSUE THREAD

**Issue by infinitesnow** [gfx-rs/wgpu-rs#644]
Empty project with `Cargo.toml`

```[package]
name = "test-package"
version = "0.1.0"
authors = ["Emanuele Dalla Longa (infinitesnow) <3xplosive.g@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.wgpu]
git = "https://github.com/gfx-rs/wgpu-rs"
rev = "d7b745e5af2251709e831b403ce720af9782064e"
features = ["trace"]
```
`cargo update` fails with
```
    Updating git repository `https://github.com/gfx-rs/wgpu-rs`
    Updating crates.io index
    Updating git repository `https://github.com/gfx-rs/wgpu`
    Updating git repository `https://github.com/zakarumych/gpu-alloc`
    Updating git repository `https://github.com/gfx-rs/naga`
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.6.0 (https://github.com/gfx-rs/wgpu-rs?rev=d7b745e5af2251709e831b403ce720af9782064e#d7b745e5)`
    ... which is depended on by `test-package v0.1.0 (/home/infinitesnow/workspace/test-package)`
versions that meet the requirements `=0.3.45` are: 0.3.45

the package `wgpu` depends on `web-sys`, with features: `GpuMapMode` but `web-sys` does not have these features.


failed to select a version for `web-sys` which could resolve this conflict
```

**Comment by Systemcluster** [comment]
This was reported in #637; A workaround for now is to copy over the `patch.crates-io` section from this projects `Cargo.toml` into your own:

```toml

[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "316c5a70fdc4a052fb65ef82bf02d52107b5671b" }
wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "316c5a70fdc4a052fb65ef82bf02d52107b5671b" }
web-sys = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "316c5a70fdc4a052fb65ef82bf02d52107b5671b" }
js-sys = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "316c5a70fdc4a052fb65ef82bf02d52107b5671b" }
```
