### ISSUE TITLE
macOS: Window losing focus will break rendering even 

### ISSUE THREAD

**Issue by seivan** [gfx-rs/wgpu-rs#75]
Using master branch wgpu and
```toml
[patch.crates-io]
gfx-hal = {git = "https://github.com/gfx-rs/gfx.git", branch = "hal-0.3" }
```

When a window loses focus, rendering no longer works. 
I can't even submit my own clear color, just get a black screen.
Occasionally this happens on launch - in other words *sometimes* it just works, but more often it just breaks. 

Recreating the swapchain will cause flickering between black and my rendering.
I recreate the swapchain for these events
`Resized(_, _) | SizeChanged(_, _) | Maximized | Hidden | Minimized`

It shouldn't flicker because it's not constantly recreating the swapchain, those events happen a few times at launch.
